const sectorViewComponents = [
  { name: "sectorId", type: "uint256", internalType: "uint256" },
  { name: "minted", type: "bool", internalType: "bool" },
  { name: "owner", type: "address", internalType: "address" },
  { name: "user", type: "address", internalType: "address" },
  { name: "userExpires", type: "uint64", internalType: "uint64" },
  { name: "rentEnabled", type: "bool", internalType: "bool" },
  { name: "pricePerDay", type: "uint256", internalType: "uint256" },
  { name: "saleEnabled", type: "bool", internalType: "bool" },
  { name: "salePrice", type: "uint256", internalType: "uint256" },
] as const;

export const moonMarketplaceAbi = [
  {
    type: "function",
    name: "registry",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
  },
  {
    type: "function",
    name: "initialSectorPrice",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "platformFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
  },
  {
    type: "function",
    name: "MUN_TO_ETH_RATE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
  },
  {
    type: "function",
    name: "FARMED_MUN_PER_DAY",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "acquireSector",
    stateMutability: "nonpayable",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setRentalPrice",
    stateMutability: "nonpayable",
    inputs: [
      { name: "sectorId", type: "uint256", internalType: "uint256" },
      { name: "pricePerDay", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setRentEnabled",
    stateMutability: "nonpayable",
    inputs: [
      { name: "sectorId", type: "uint256", internalType: "uint256" },
      { name: "enabled", type: "bool", internalType: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "rentSector",
    stateMutability: "nonpayable",
    inputs: [
      { name: "sectorId", type: "uint256", internalType: "uint256" },
      { name: "numberOfDays", type: "uint64", internalType: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "listForSale",
    stateMutability: "nonpayable",
    inputs: [
      { name: "sectorId", type: "uint256", internalType: "uint256" },
      { name: "price", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelListing",
    stateMutability: "nonpayable",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "buyListedSector",
    stateMutability: "nonpayable",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "balances",
    stateMutability: "view",
    inputs: [{ name: "sectorId", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "getMUNBalance",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "popUpBalance",
    stateMutability: "payable",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "sendMUN",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount_MUN", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "farmedBalance",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "farmCheckpoint",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
  },
  {
    type: "function",
    name: "claimFarmedBalance",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "treasury",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
  },
  {
    type: "function",
    name: "platformBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "withdrawPlatformFunds",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setInitialSectorPrice",
    stateMutability: "nonpayable",
    inputs: [{ name: "newPrice", type: "uint256", internalType: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setPlatformFeeBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFeeBps", type: "uint16", internalType: "uint16" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setTreasury",
    stateMutability: "nonpayable",
    inputs: [{ name: "newTreasury", type: "address", internalType: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getSector",
    stateMutability: "view",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct MoonMarketplace.SectorView",
        components: sectorViewComponents,
      },
    ],
  },
  {
    type: "function",
    name: "getSectors",
    stateMutability: "view",
    inputs: [{ name: "sectorIds", type: "uint256[]", internalType: "uint256[]" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct MoonMarketplace.SectorView[]",
        components: sectorViewComponents,
      },
    ],
  },
  {
    type: "event",
    name: "SectorAcquired",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "owner", type: "address", indexed: true, internalType: "address" },
      { name: "price", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RentalPriceChanged",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "pricePerDay", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RentAvailabilityChanged",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "enabled", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SectorRented",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "renter", type: "address", indexed: true, internalType: "address" },
      { name: "expiresAt", type: "uint64", indexed: false, internalType: "uint64" },
      { name: "totalPrice", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SectorListed",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "price", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SectorListingCancelled",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SectorSold",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "price", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TreasuryChanged",
    inputs: [
      { name: "previous", type: "address", indexed: true, internalType: "address" },
      { name: "current", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlatformFundsWithdrawn",
    inputs: [
      { name: "to", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { name: "user", type: "address", indexed: false, internalType: "address" },
      { name: "MUN_value", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Sent",
    inputs: [
      { name: "from", type: "address", indexed: false, internalType: "address" },
      { name: "to", type: "address", indexed: false, internalType: "address" },
      { name: "amount_MUN", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FarmedBalanceClaimed",
    inputs: [
      { name: "account", type: "address", indexed: true, internalType: "address" },
      { name: "amount_MUN", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "error", name: "AccessControlBadConfirmation", inputs: [] },
  {
    type: "error",
    name: "AccessControlUnauthorizedAccount",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "neededRole", type: "bytes32", internalType: "bytes32" },
    ],
  },
  {
    type: "error",
    name: "AlreadyRented",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "CannotBuyOwnSector",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "CannotRentOwnSector",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "FailedCall", inputs: [] },
  {
    type: "error",
    name: "FeeTooHigh",
    inputs: [
      { name: "requested", type: "uint16", internalType: "uint16" },
      { name: "maximum", type: "uint16", internalType: "uint16" },
    ],
  },
  {
    type: "error",
    name: "InsufficientBalance",
    inputs: [
      { name: "balance", type: "uint256", internalType: "uint256" },
      { name: "needed", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InsufficientPayment",
    inputs: [
      { name: "required", type: "uint256", internalType: "uint256" },
      { name: "provided", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InsufficientPlatformBalance",
    inputs: [
      { name: "requested", type: "uint256", internalType: "uint256" },
      { name: "available", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InvalidDuration",
    inputs: [{ name: "numberOfDays", type: "uint64", internalType: "uint64" }],
  },
  {
    type: "error",
    name: "InvalidSector",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "NotListed",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "NotSectorOwner",
    inputs: [
      { name: "sectorId", type: "uint256", internalType: "uint256" },
      { name: "caller", type: "address", internalType: "address" },
    ],
  },
  { type: "error", name: "NothingToWithdraw", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "RentNotEnabled",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "SectorAlreadyClaimed",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "SectorCurrentlyRented",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "SectorNotMinted",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;
