const sectorViewComponents = [
  { name: "sectorId", type: "uint256", internalType: "uint256" },
  { name: "minted", type: "bool", internalType: "bool" },
  { name: "owner", type: "address", internalType: "address" },
  { name: "user", type: "address", internalType: "address" },
  { name: "userExpires", type: "uint64", internalType: "uint64" },
  { name: "rentEnabled", type: "bool", internalType: "bool" },
  { name: "pricePerDay", type: "uint256", internalType: "uint256" },
  { name: "saleEnabled", type: "bool", internalType: "bool" },
  { name: "salePrice", type: "uint256", internalType: "uint256" },
] as const;

export const moonMarketplaceAbi = [
  {
    type: "function",
    name: "registry",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
  },
  {
    type: "function",
    name: "initialSectorPrice",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "platformFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
  },
  {
    type: "function",
    name: "acquireSector",
    stateMutability: "payable",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setRentalPrice",
    stateMutability: "nonpayable",
    inputs: [
      { name: "sectorId", type: "uint256", internalType: "uint256" },
      { name: "pricePerDay", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setRentEnabled",
    stateMutability: "nonpayable",
    inputs: [
      { name: "sectorId", type: "uint256", internalType: "uint256" },
      { name: "enabled", type: "bool", internalType: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "rentSector",
    stateMutability: "payable",
    inputs: [
      { name: "sectorId", type: "uint256", internalType: "uint256" },
      { name: "numberOfDays", type: "uint64", internalType: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "listForSale",
    stateMutability: "nonpayable",
    inputs: [
      { name: "sectorId", type: "uint256", internalType: "uint256" },
      { name: "price", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelListing",
    stateMutability: "nonpayable",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "buyListedSector",
    stateMutability: "payable",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimableBalance",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "platformBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "withdrawRentalIncome",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawPlatformFunds",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setInitialSectorPrice",
    stateMutability: "nonpayable",
    inputs: [{ name: "newPrice", type: "uint256", internalType: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setPlatformFeeBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFeeBps", type: "uint16", internalType: "uint16" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getSector",
    stateMutability: "view",
    inputs: [{ name: "sectorId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct MoonMarketplace.SectorView",
        components: sectorViewComponents,
      },
    ],
  },
  {
    type: "function",
    name: "getSectors",
    stateMutability: "view",
    inputs: [{ name: "sectorIds", type: "uint256[]", internalType: "uint256[]" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct MoonMarketplace.SectorView[]",
        components: sectorViewComponents,
      },
    ],
  },
  {
    type: "event",
    name: "SectorAcquired",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "owner", type: "address", indexed: true, internalType: "address" },
      { name: "price", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RentalPriceChanged",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "pricePerDay", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RentAvailabilityChanged",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "enabled", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SectorRented",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "renter", type: "address", indexed: true, internalType: "address" },
      { name: "expiresAt", type: "uint64", indexed: false, internalType: "uint64" },
      { name: "totalPrice", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SectorListed",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "price", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SectorListingCancelled",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SectorSold",
    inputs: [
      { name: "sectorId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "price", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RentalIncomeWithdrawn",
    inputs: [
      { name: "account", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlatformFundsWithdrawn",
    inputs: [
      { name: "to", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "error", name: "InvalidSector", inputs: [] },
  { type: "error", name: "SectorAlreadyClaimed", inputs: [] },
  { type: "error", name: "InsufficientPayment", inputs: [] },
  { type: "error", name: "SectorNotMinted", inputs: [] },
  { type: "error", name: "RentNotEnabled", inputs: [] },
  { type: "error", name: "AlreadyRented", inputs: [] },
  { type: "error", name: "InvalidDuration", inputs: [] },
  { type: "error", name: "CannotRentOwnSector", inputs: [] },
  { type: "error", name: "NotListed", inputs: [] },
  { type: "error", name: "CannotBuyOwnSector", inputs: [] },
  { type: "error", name: "SectorCurrentlyRented", inputs: [] },
  { type: "error", name: "NotSectorOwner", inputs: [] },
  { type: "error", name: "NothingToWithdraw", inputs: [] },
] as const;
